// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitrineApp_R.Data;

namespace VitrineApp_R.Migrations
{
    [DbContext(typeof(VitrineApp_RContext))]
    partial class VitrineApp_RContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ConsoleApp2.Serialization.CoresDisponiveis", b =>
                {
                    b.Property<string>("hexValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Itemid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeCor")
                        .HasColumnType("TEXT");

                    b.HasKey("hexValue");

                    b.HasIndex("Itemid");

                    b.ToTable("CoresDisponiveis");
                });

            modelBuilder.Entity("ConsoleApp2.Serialization.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("imageLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("price")
                        .HasColumnType("TEXT");

                    b.Property<string>("productType")
                        .HasColumnType("TEXT");

                    b.Property<string>("tagList")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ConsoleApp2.Serialization.CoresDisponiveis", b =>
                {
                    b.HasOne("ConsoleApp2.Serialization.Item", null)
                        .WithMany("coresDisponiveis")
                        .HasForeignKey("Itemid");
                });

            modelBuilder.Entity("ConsoleApp2.Serialization.Item", b =>
                {
                    b.Navigation("coresDisponiveis");
                });
#pragma warning restore 612, 618
        }
    }
}
